/* ALL ACTIONS TO USE */

/* BASE ERASE */
const GET_USERINFO_REQUEST = "GET_USERINFO_REQUEST";
const GET_USERINFO_SUCCESS = "GET_USERINFO_SUCCESS";
const GET_USERINFO_ERROR = "GET_USERINFO_ERROR";

const GET_USER_REPOS_REQUEST = "GET_USER_REPOS_REQUEST";
const GET_USER_REPOS_SUCCESS = "GET_USER_REPOS_SUCCESS";
const GET_USER_REPOS_ERROR = "GET_USER_REPOS_ERROR";

/* LOADER */
const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";

/* MODAL */
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const ACCEPT_MODAL = "ACCEPT_MODAL";

export {
	GET_USERINFO_REQUEST,
	GET_USERINFO_SUCCESS,
	GET_USERINFO_ERROR,
	GET_USER_REPOS_REQUEST,
	GET_USER_REPOS_SUCCESS,
	GET_USER_REPOS_ERROR,
	SHOW_LOADER,
	HIDE_LOADER,
	SHOW_MODAL,
	HIDE_MODAL,
	ACCEPT_MODAL,
};
